# Generated by Django 2.1.1 on 2019-03-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genus", models.TextField()),
                ("species", models.TextField()),
                ("fangs", models.TextField()),
                ("toxicity", models.TextField()),
                ("rating", models.TextField()),
                ("common_name", models.TextField()),
                ("recommended_snakes", models.TextField()),
            ],
        )
    ]
