# Generated by Django 2.1.1 on 2019-03-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snekbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recommended_snakes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snekbook.Post'),
        ),
    ]
