# Generated by Django 2.1.1 on 2019-03-07 06:13

from django.db import migrations

from django.db import migrations
import csv
from ast import literal_eval

def populate_snakes(apps, schema_editor):
    Snake = apps.get_model('snekbook', 'Snake')

    with open("data_scrubber/snake_db_enriched.csv") as f:
        snake_db_reader = csv.DictReader(f)
        django_id_to_recommended_snake_idx = {}
        # initial pass; create all our snakes
        for snake in snake_db_reader:
            s = Snake(
                genus=snake["genus"],
                species=snake["species"],
                fangs=snake["fangs"],
                toxicity=snake["toxicity"],
                rating=snake["rating"],
                common_name=snake["common_name"]
            )
            s.save()
            django_id_to_recommended_snake_idx[s.id] = \
                literal_eval(snake["recommended_snakes"])
        # second pass; assign recommended_snakes
        for s in Snake.objects.all():
            s.recommended_snakes.set(
                Snake.objects.filter(pk__in=django_id_to_recommended_snake_idx[s.id])
            )
            s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('snekbook', '0005_auto_20190307_0613'),
    ]

    operations = [
        migrations.RunPython(populate_snakes),
    ]
