# Generated by Django 2.1.1 on 2019-06-10 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("snekbook", "0009_comment_author")]

    operations = [
        migrations.AddField(
            model_name="snake",
            name="likers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        )
    ]
