version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Pipenv install dependencies
          command: |
              sudo pip install pipenv \
              && pipenv install --dev
      # - run:
      #     name: Download selenium
      #     command: |
      #       curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start selenium
      #     command: |
      #       mkdir test-reports/
      #       java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true
      - run:
          name: Run tests
          command: |
            mkdir -p ./testreports/
            make test PYTEST_ARGS="--junitxml='./testreports/results.xml'"
      - store_test_results:
          path: testreports
  # deploy:
  #     docker:
  #       - image: buildpack-deps:trusty
  #     steps:
  #       - checkout
  #       - run:
  #           name: Deploy Master to Heroku
  #           command: |
  #             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master